version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DominioPedidos"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-z6trzgzyvobn"
s3_prefix = "DominioPedidos"
region = "us-east-1"
profile = "dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
