AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MasterDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: 'CloudFormation'
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: DBUser
      MasterUserPassword: DBPassword
     