version: 0.2

phases: 
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd ./src
    build:
      commands:
        - pip install -r requirements.txt -t .
        - python -m pytest
  artifacts:
    files: 
      - scr/app.py
      - src/requimentes.txt
  name: EldoradoBuild